
var menuApp = angular.module("MenuApp", []);
if (language == 'es') {

  menuApp.controller("MenuCtrl", function($scope) {

    $scope.Yes = 'Si';
    $scope.No = 'No';
    $scope.Title = 'Marcador Animal Allies (v2.0)';
    $scope.Scorer = 'Marcador';
    $scope.Timers = 'Cronómetros';
    $scope.Saves = 'Guardados';
    $scope.Points = 'Puntos';
      PointsLang = 'Puntos';
      GraphTitle = 'Diagrama de línea de puntajes';
      GraphLegend = 'Marcar';
    $scope.Start = 'Inicio';
    $scope.Reset = 'Reiniciar';
    $scope.Stop = 'Parar';
    $scope.SaveScore = 'Guardar marcador';  
    $scope.LoadSave = 'Cargar marcador';  
    $scope.DeleteSave = 'Borrar todos los marcadores!';  
    DeletedSave = 'Se borra todos los marcadores :-( !!!!';
    $scope.ImportSave = 'Importar Marcadores Guardados';
    $scope.ExportSave = 'Exportar Marcadores Guardados';

    $scope.M01 = 'Transporte del tiburón';
    $scope.M01a = '¿El Tanque y Tiburón están completamente dentro de la Zona (caja izquierda)?';
    $scope.M01b = '¿El Tanque y Tiburón están completamente dentro de la Zona (caja derecha)?';
    $scope.M01c = '¿El Tiburón está tocando únicamente el suelo del tanque?';
    $scope.M01d = 'Nota: Después del inicio para esta misión, no está permitido que nada, excepto el Tanque, toque en ningún momento el Tiburón.';
    $scope.M02 = 'Acción del perro lazarillo';
    $scope.M02a = '¿La Valla de Advertencia está bajada?';
    $scope.M02b = 'Nota: La Valla debe estar bajada porque el Robot la ha cruzado completamente desde el oeste, después de transitar entre las Barreras.';
    $scope.M03 = 'Conservación animal ';
    $scope.M03a = '¿Cuantas parejas de animales hay en ambas mesas? ';
    $scope.M03b = 'Nota: Cada pareja debe ser creada por la rotación del Modelo de Misión de Conservación animal. ';
    $scope.M04 = 'Alimentación';
    $scope.M04a = '¿Cuántos trozos de Comida está completamente dentro de una Zona para Comida? ';
    $scope.M04b = 'Nota: Si hay más de un trozo de Comida en una Zona, todas deben coincidir.';
    $scope.M05 = 'Biomemitismo';
    $scope.M05a = '¿La Pared Biomimética soporta completamente todo el peso de la Salamanquesa Blanca?';
    $scope.M05b = '¿La Pared Biomimética soporta completamente todo el peso del Robot?';
    $scope.M05c = 'Nota: Ninguna parte del objeto puede estar en contacto con algo que no sea la Pared Biomimética y/o la Lagartija Verde, exceptuando que los dos objetos puntuables pueden contactar entre ellos.';
    $scope.M06 = 'Ordeño automático  ';
    $scope.M06a = '¿Ha salido toda la Leche y todo el Estiércol?  ';
    $scope.M06b = '¿Ha salido toda la Leche pero nada de Estiércol?  ';
    $scope.M06c = 'Nota: La Leche y/o el Estiércol salió únicamente por el movimiento del Robot actuando sobre la palanca roja.';
    $scope.M07 = 'Liberación de pandas';
    $scope.M07a = '¿La bisagra se observa completamente abierta en sentido horario?  ';
    $scope.M08 = 'Recuperación de cámaras  ';
    $scope.M08a = '¿Está la Cámara completamente dentro de la Base?  ';
    $scope.M09 = 'Adiestramiento e investigación  ';
    $scope.M09a = '¿El Perro y el Adiestrador están completamente dentro de la Zona de Adiestramiento e Investigación?';
    $scope.M09b = '¿La Zoóloga está completamente dentro de la Zona de Adiestramiento e Investigación?';
    $scope.M09c = '¿Cuántas Muestras de Excrementos están completamente dentro de la Zona de Adiestramiento e Investigación?';
    $scope.M09d = 'Nota: Solo se puede transportar una Muestra de Excrementos cada vez.  ';
    $scope.M10 = 'Apicultura ';
    $scope.M10a = '¿La Abeja está sobre la Colmena y no hay Miel en la Colmena?';
    $scope.M10b = '¿La Abeja está sobre la Colmena y la Miel está completamente dentro de la Base?';
    $scope.M11 = 'Prótesis ';
    $scope.M11a = '¿La Prótesis está colocada en la Mascota Y no la sostiene el Árbitro?';
    $scope.M11b = '¿La Prótesis está colocada en la Mascota Y la Mascota está completamente dentro de la Zona de la Granja?';
    $scope.M12 = 'Foca en base ';
    $scope.M12a = '¿La Foca está completamente dentro de la Base y no está rota?';
    $scope.M13 = 'Leche en la base  ';
    $scope.M13a = '¿Las tres unidades de Leche están completamente dentro de la Base?';
    $scope.M14 = 'Leche en la rampa  ';
    $scope.M14a = '¿La Rampa soporta completamente las tres unidades de Leche?';
    $scope.M14b = '¿La Rampa soporta completamente las tres unidades de Leche Y son los únicos objetos que tocan la Rampa?';
    $scope.M14c = '¿La Rampa soporta completamente las tres unidades de Leche Y son los únicos objetos que tocan la Rampa Y todas están de pie?';
    $scope.M15 = 'Todas las muestras  ';
    $scope.M15a = '¿Las siete Muestras de Excrementos están completamente dentro de la Zona de Adiestramiento e Investigación?';
    $scope.Penalty = 'Penalizaciones  ';
    $scope.Penaltya = '¿Cuántas Muestras de Excrementos están dentro del triángulo blanco?  ';

  });
} else if (language == 'de') {

  menuApp.controller("MenuCtrl", function($scope) {

    $scope.Yes = 'Ja';
    $scope.No = 'Nein';
    $scope.Title = 'Animal Allies Punkterechner (v2.0)';
    $scope.Scorer = 'Punkterechner';
    $scope.Timers = 'Timer';
    $scope.Saves = 'Gespeicherte Punktzahlen';
    $scope.Points = 'Punkte';
    PointsLang = 'Punkte';
      GraphTitle = 'Liniendiagramm der Punktzahlen';
      GraphLegend = 'Punktzahl';
    $scope.Start = 'Start';
    $scope.Reset = 'Zurücksetzen';
    $scope.Stop = 'Stop';
    $scope.SaveScore = 'Punktzahl Speichern';  
    $scope.LoadSave = 'Punktzahl Laden';  
    $scope.DeleteSave = 'Alle gespeicherten punktzahlen löschen!';  
    DeletedSave = 'Löscht alle gespeicherten punktzahlen :-( !!!!';
    $scope.ImportSave = 'Gespeicherte Spielstände Importieren';
    $scope.ExportSave = 'Gespeicherte Spielstände Exportieren';

    $scope.M01 = 'Hai-Transport';
    $scope.M01a = 'Sind das Becken und der Hai komplett am ersten Zielort (linkes Viereck)? ';
    $scope.M01b = 'Sind das Becken und der Hai komplett am zweiten Zielort (rechtes Viereck)? ';
    $scope.M01c = 'Berührt der Hai nur den Beckenboden (nicht die Wände des Beckens)? ';
    $scope.M01d = 'Hinweis: Nie darf etwas den Hai berühren, außer dem Becken!';

    $scope.M02 = 'Assistenzhund';
    $scope.M02a = 'Liegt der Warnzaun waagerecht?';
    $scope.M02b = 'Hinweis: Der Warnzaun liegt waagerecht auf der Matte, weil der Roboter ihn komplett aus westlicher Richtung überquert hat, nachdem er zwischen den Leitplanken durch gefahren ist.';
    $scope.M03 = 'Artenschutz';
    $scope.M03a = 'Wie viele Paare derselben Tierart befinden sich komplett auf der gleichen Seite des Tisches? ';
    $scope.M03b = 'Hinweis:  Jedes Paar muss durch die Drehung des Artenschutzmodells zusammengeführt werden.';
    $scope.M04 = 'Fütterung';
    $scope.M04a = 'Wie viele Futterrationen befinden sich komplett in den Zielbereichen? ';
    $scope.M04b = 'Hinweis: Die Rechtecke in den Tierbereichen gehören nicht zum Zielbereich. Wenn sich mehrere Futterrationen in einem Zielbereich befinden, müssen diese die gleiche Farbe haben.';
    $scope.M05 = 'Bionik';
    $scope.M05a = 'Hängt der weiße Gecko komplett an der Wand';
    $scope.M05b = 'Hängt der Roboter komplett an der Wand? ';
    $scope.M05c = 'Hinweis: Um Punkte zu erzielen, dürfen sowohl der weiße Gecko als auch der Roboter nur mit der Wand und/oder dem grünen Gecko in Berührung sein. Ausnahme: Die beiden Wertungsobjekte dürfen sich gegenseitig berühren.';
    $scope.M06 = 'Melkmaschine';
    $scope.M06a = 'Sind Milch und Kot heraus gerollt? ';
    $scope.M06b = 'Ist die Milch herausgerollt, aber kein Kot? ';
    $scope.M06c = 'Hinweis: Die Milch und/oder der Kot sind nur durch die Bewegung des roten Hebels heraus gerollt.';
    $scope.M07 = 'Panda-Auswilderung ';
    $scope.M07a = 'Ist das Tor vollständig geöffnet (im Uhrzeigersinn)?';
    $scope.M08 = 'Kamera abholen';
    $scope.M08a = 'Befindet sich die Kamera komplett in der Base?';
    $scope.M09 = 'Training und Forschung';
    $scope.M09a = 'Befindet sich der Trainer mit Hund komplett in der Trainings- und Forschungsstation? ';
    $scope.M09b = 'Befindet sich die Zoologin komplett in der Trainings- und Forschungsstation?';
    $scope.M09c = 'Wie viele Kot-Stücke befinden sich komplett in der Trainings- und Forschungsstation?';
    $scope.M09d = 'Hinweis: Es darf immer nur ein Kothaufen transportiert werden.';
    $scope.M10 = 'Bienenzucht';
    $scope.M10a = 'Ist die Biene auf dem Bienenstock und es befindet sich kein Honig mehr im Bienenstock? ';
    $scope.M10b = 'Ist die Biene auf dem Bienenstock und der Honig befindet sich komplett in der Base?';
    $scope.M11 = 'Prothesen';
    $scope.M11a = 'Ist die Prothese am Tier UND wird nicht vom Schiedsrichter gehalten? ';
    $scope.M11b = 'Ist die Prothese am Tier UND das Tier befindet sich komplett im Bereich “Bauernhof”?';
    $scope.M12 = 'Seehund';
    $scope.M12a = 'Befindet sich der Seehund komplett in der Base und ist nicht “verletzt” (zerbrochen)?';
    $scope.M13 = 'Milch in der Base ';
    $scope.M13a = 'Sind die 3 Milchbehälter komplett in der Base?';
    $scope.M14 = 'Milch auf der Rampe ';
    $scope.M14a = 'Werden alle 3 Milchbehälter komplett von der Rampe getragen? ';
    $scope.M14b = 'Werden alle 3 Milchbehälter komplett von der Rampe getragen UND werden sie nur von der Rampe getragen und berührt nichts anderes die Rampe? ';
    $scope.M14c = 'Werden alle 3 Milchbehälter komplett von der Rampe getragen UND werden sie nur von der Rampe getragen und berührt nichts anderes die Rampe UND stehen alle drei aufrecht?';
    $scope.M15 = 'Kot';
    $scope.M15a = 'Befinden sich alle 7 Kothaufen komplett in der Trainings- und Forschungsstation?';
    $scope.Penalty = 'Strafpunkte';
    $scope.Penaltya = 'Wie viele Strafpunkte befinden sich im weißen Dreieck in der Ecke des Spielfelds?';

  });

} else if (language == 'pt-br') {
  menuApp.controller("MenuCtrl", function($scope) {

    $scope.Yes = 'Sim';
    $scope.No = 'Não';
    $scope.Title = 'Pontuador do Animal Allies (v2.0)';
    $scope.Scorer = 'Pontuador';
    $scope.Timers = 'Cronômetros';
    $scope.Saves = 'Salvos';
    $scope.Points = 'Pontos';
      GraphTitle = 'Gráfico de linha de partituras';
      GraphLegend = 'Marca';
    PointsLang = 'Pontos';
    $scope.Start = 'Começar';
    $scope.Reset = 'Reiniciar';
    $scope.Stop = 'Pare';
    $scope.SaveScore = 'Salvar Pontuação';  
    $scope.LoadSave = 'Carregar Pontuação';  
    $scope.DeleteSave = 'Apagar tudo Salva!';  
    DeletedSave = 'Eliminados Todos Salva :-( !!!!';
    $scope.ImportSave = 'Importar Pontuação Salvo';
    $scope.ExportSave = 'Exportar Pontuação Salvo';

    $scope.M01 = 'TRANSPORTE DE TUBARÃO';
    $scope.M01a = 'O Tanque e Tubarão estão completamente no Alvo 1 (retângulo à esquerda)?';
    $scope.M01b = 'O Tanque e Tubarão estão completamente no Alvo 2 (retângulo à direita)?';
    $scope.M01c = 'O Tubarão está tocando apenas o fundo do tanque e nenhuma parede?';

    $scope.M02 = 'AÇÃO DO CÃO-GUIA';
    $scope.M02a = 'A Cerca de Proteção está abaixada e o robô cruzou-a completamente do Oeste?';

    $scope.M03 = 'CONSERVAÇÃO DOS ANIMAIS';
    $scope.M03a = 'Quantos animais idênticos estão completamente no mesmo lado da mesa?';
    $scope.M04 = 'ALIMENTAÇÃO';
    $scope.M04a = 'Quantas peças de Comida combinadas estão completamente na área alvo?';
    $scope.M05 = 'BIOMIMÉTICA';
    $scope.M05a = 'A Parede de Biomimética suporta todo o peso do Lagarto Branco?';
    $scope.M05b = 'A Parede de Biomimética suporta todo o peso do robô?';
    $scope.M06 = 'AUTOMAÇÃO DE ORDENHA';
    $scope.M06a = 'O Leite e Estrume rolaram todos para fora?';
    $scope.M06b = 'Todo Leite rolou para fora, mas nenhum Estrume?';
    $scope.M07 = 'LIBERTAÇÃO DO PANDA';
    $scope.M07a = 'A alavanca está completamente aberta no sentido horário?';
    $scope.M08 = 'RECUPERAÇÃO DA CÂMERA';
    $scope.M08a = 'A Câmera está completamente na Base?';
    $scope.M09 = 'TREINAMENTO E PESQUISA';
    $scope.M09a = 'O Cão e o Treinador estão completamente na Área de Treinamento e Pesquisa?';
    $scope.M09b = 'O Zoólogo está completamente na Área de Treinamento e Pesquisa?';
    $scope.M09c = 'Quantas Amostras de Estrume estão completamente na Área de Treinamento e Pesquisa?';
    $scope.M10 = 'APICULTURA';
    $scope.M10a = 'A Abelha está na Colmeia e não há Mel na mesma?';
    $scope.M10b = 'A Abelha está na Colmeia e o Mel está completamente na Base?';
    $scope.M11 = 'PRÓTESE';
    $scope.M11a = 'A Prótese está ajustada no Animal de Estimação E não está segurada pelo Juiz?';
    $scope.M11b = 'A Prótese está ajustada no Animal de Estimação E o mesmo está completamente na sua Fazenda?';
    $scope.M12 = 'FOCA NA BASE';
    $scope.M12a = 'A Foca está completamente na Base e não está quebrada?';
    $scope.M13 = 'LEITE NA BASE';
    $scope.M13a = 'Todos os três Leites estão completamente na Base?';
    $scope.M14 = 'LEITE NA RAMPA';
    $scope.M14a = 'Todos os três Leites estão completamente apoiados pela Rampa?';
    $scope.M14b = 'Todos os três Leites estão completamente apoiados pela Rampa E são as únicas coisas apoiadas pela Rampa?';
    $scope.M14c = 'Todos os três Leites estão completamente apoiados pela Rampa E são as únicas coisas apoiadas pela Rampa E estão todos de pé?';
    $scope.M15 = 'TODAS AS AMOSTRAS';
    $scope.M15a = 'Todas as sete Amostras de Estrume estão completamente na Área de Treinamento e Pesquisa?';
    $scope.Penalty = 'PENALIDADES';
    $scope.Penaltya = 'Quantas Amostras de Estrume estão no triângulo branco?';
  });

} else if (language == "nl") {
  menuApp.controller("MenuCtrl", function($scope) {

    $scope.Yes = 'Ja';
    $scope.No = 'Nee';
    $scope.Title = 'Animal Allies Puntenteller (v2.0)';
    $scope.Scorer = 'Puntenteller';
    $scope.Timers = 'Timers';
    $scope.Saves = 'Saves';
    $scope.Points = 'Punten';
      GraphTitle = 'lijngrafiek van scores';
      GraphLegend = 'Aantal punten';
    PointsLang = 'Punten';
    $scope.Start = 'Begin';
    $scope.Reset = 'Resetten';
    $scope.Stop = 'Stop';
    $scope.SaveScore = 'Save Score';  
    $scope.LoadSave = 'Laadt Score';  
    $scope.DeleteSave = 'Delete All Slaat!';  
    DeletedSave = 'Schrapte Alle Slaat :-( !!!!';
    $scope.ImportSave = 'Importeren Opgeslagen Score';
    $scope.ExportSave = 'Exporteert Opgeslagen Score';

    $scope.M01 = 'HAAIENVERVOER';
    $scope.M01a = 'Zijn de tank en de haai compleet in gebied 1 (linker box)?';
    $scope.M01b = 'Zijn de tank en de haai compleet in gebied 2 (rechter box)?';
    $scope.M01c = 'Raakt de haai alleen de bodem van de tank aan?';
    $scope.M01d = 'Opmerking: Na de start is het niet toegestaan date er iets ander dan de haai de tank raakt';
    $scope.M02 = 'HULPHOND IN ACTIE';
    $scope.M02a = 'Is het waarschuwinshek omlaag?';
    $scope.M02b = 'Opmerking: Waarschuwingshek moet omlaag zijn, omdat de robot dit volledig doorkruist van het westen, nadat hij tussen de slagbomen heeft gereden';
    $scope.M03 = 'DIERENBESCHERMING';
    $scope.M03a = 'Hoeveel identieke paren van dieren zijn op beide tafels?';
    $scope.M03b = 'Opmerking: Elk paar moet worden gecreëerd door de rotatie van de Animal Conservation Mission Model.';
    $scope.M04 = 'VOEREN';
    $scope.M04a = 'Hoeveel stukken voedsel zijn volledig in een dierengebied?';
    $scope.M04b = 'Opmerking: Als er meerdere stukken voedsel zijn in een gebied, moeten ze allemaal met elkaar overeenkomen.';
    $scope.M05 = 'Biomimicry';
    $scope.M05a = 'Draagt de Biomimicry Muur al het hele gewicht van de Witte Gekko?';
    $scope.M05b = 'Draagt de Biomimicry Muur al het hele gewicht van de robot?';
    $scope.M05c = 'Opmerking: Niets van een scoring object mag in contact zijn met iets anders dan de Biomimicry muur en / of groene Gekko, De twee scorende voorwerpen mogen wel met elkaar in contact komen.';
    $scope.M06 = 'MELKMACHINE';
    $scope.M06a = 'Melk en mest zijn uitgerold?';
    $scope.M06b = 'Alle Melk is uitgerold, maar de mest niet';
    $scope.M06c = 'Opmerking: De enige beweging die de robot maakt om de melk en / of mest te bewegen komt door het verplaatsen van de rode hendel';
    $scope.M07 = 'PANDA VRIJLATING';
    $scope.M07a = 'Is de hendel volledige open, met de klok mee?';
    $scope.M08 = 'CAMERA TERUGHALEN';
    $scope.M08a = 'Is de camera volledig in de basis?';
    $scope.M09 = 'TRAINING EN ONDERZOEK';
    $scope.M09a = 'Zijn de Hond en Trainer volledig in het trainings-  en onderzoekgebied?';
    $scope.M09b = 'Is de dierdeskundige volledig in het trainings- en onderzoekgebied?';
    $scope.M09c = 'Hoeveel mest Monsters zijn volledig in het trainings- en onderzoekgebied?';
    $scope.M09d = 'Opmerking: Er mag slechts één mest monster per keer worden vervoerd';
    $scope.M10 = 'BIJEN HOUDEN';
    $scope.M10a = 'Is de bij op de bijenkorf en er is geen honing in de bijenkorf?';
    $scope.M10b = 'Is de bij op de bijenkorf en is er honing in de basis?';
    $scope.M11 = 'PROTHESE';
    $scope.M11a = 'Is de protese bevestigd aan het huisdier dus niet in bezit van de scheidsrechter?';
    $scope.M11b = 'Is de protese bevestigd aan het huisdier en is het huisdier volledig in het boerderijgebied?';
    $scope.M12 = 'ZEEHOND';
    $scope.M12a = 'Is de zeehond volledig in de basis en niet beschadigd?';
    $scope.M13 = 'MELK IN BASIS';
    $scope.M13a = 'Zijn  alle 3 de melk volledig in de basis?';
    $scope.M14 = 'MELK OP DE OPRIT';
    $scope.M14a = 'Zijn alle drie de melk volledig ondersteund door de Ramp?';
    $scope.M14b = 'Zijn alle drie de melk ondersteund door de Ramp en ze zijn de enige dingen die de ramp aanraken?';
    $scope.M14c = 'Zijn alle drie de melk volledig ondersteund door de Ramp en ze zijn de enige dingen die de ramp aanraken en staan ze allemaal rechtop?';
    $scope.M15 = 'ALLE MONSTERS';
    $scope.M15a = 'Zijn alle zeven mest monsters volledig in het trainings- en onderzoeksgebied?';
    $scope.Penalty = 'STRAFPUNTEN';
    $scope.Penaltya = 'Hoeveel mest monsters zijn er in het witte driehoek gebied?';

  });

} else if (language == "hu"){

  menuApp.controller("MenuCtrl", function($scope) {

    $scope.Yes = 'Igen';
    $scope.No = 'Nem';
    $scope.Title = 'Animal Allies Pontszámító (v2.0)';
    $scope.Scorer = 'Scorer';
    $scope.Timers = 'Időzítők';
    $scope.Saves = 'Mentések';
    $scope.Points = 'Pontok';
      GraphTitle = 'Line Graph of Scores';
      GraphLegend = 'Scores';
    PointsLang = 'Points';
    $scope.Start = 'Start';
    $scope.Reset = 'Reset';
    $scope.Stop = 'Stop';
    $scope.SaveScore = 'Pontok mentése';  
    $scope.LoadSave = 'Pontok betöltése';  
    $scope.DeleteSave = 'Delete All Saves!';  
    DeletedSave = 'Deleted all saves :-( !!!!';
    $scope.ImportSave = 'Import Saved Scores';
    $scope.ExportSave = 'Export Saved Scores';

    $scope.M01 = 'A cápa szállítása';
    $scope.M01a = 'A tartály és a cápa teljesen az 1. célterületen vannak? (bal oldali doboz)';
    $scope.M01b = 'A tartály és a cápa teljesen az 2. célterületen vannak? (jobb oldali doboz)';
    $scope.M01c = 'A cápa csak a tartály padlójához ér hozzá?';
    $scope.M01d = 'Megjegyzés: Az indítás után semmi sem érintheti a cápát a tartályon kívűl.';
    $scope.M02 = 'Vakvezető kutya';
    $scope.M02a = 'A figyelmeztető kerítés vízszintesen lehajtva helyezkedik el?';
    $scope.M02b = 'A figyelmeztető kerítés vízszintesen fekszik a pályán, mert a robot nyugati irányból teljesen áthajtott rajta, miután áthaladt a korlátok között?';
    $scope.M03 = 'Állatfajok megőrzése';
    $scope.M03a = 'Hány azonos fajhoz tartozó állatpár van teljes terjedelmében ugyanazon az oldalon - a két asztalon összesen?';
    $scope.M03b = 'Megjegyzés: Akkor számít párnak ha az állatmegőrzés modellen pörgettük át a másik asztalhoz.';
    $scope.M04 = 'Etetés';
    $scope.M04a = 'Hány adag eledel van a kijelölt körökben??';
    $scope.M04b = 'Megjegyzés: Egy körben csak azonos színű eledelek lehetnek.';
    $scope.M05 = 'Biomimikri';
    $scope.M05a = 'A fehér gekkó teljes terjedelmében a biomimikri falon lóg?';
    $scope.M05b = 'A robot teljes terjedelmében a biomimikri falon lóg?';
    $scope.M05c = 'Megjegyzés: A pontszerző tárgy nem érhet semmihez a falon és a zöld gekkón kívűl. Kivétel ez alól, ha a két pontszerző tárgy egymáshoz ér.';
    $scope.M06 = 'Fejőgép';
    $scope.M06a = 'A tej és a trágya is kiesett?';
    $scope.M06b = 'Csak a tej esett ki, a trágya nem?';
    $scope.M06c = 'Megjegyzés: A tej és/vagy a trágya csak a piros kar mozgatása során gurultak ki a gépből.';
    $scope.M07 = 'Panda szabadonengedése';
    $scope.M07a = 'A kapu teljesen ki van nyitva?';
    $scope.M08 = 'Kamera megszerzése';
    $scope.M08a = 'A kamera a bázison van?';
    $scope.M09 = 'Kiképzés és kutatás';
    $scope.M09a = 'A kiképző a kutyával együtt teljes terjedelmében a kiképző- és kutatóállomáson van?';
    $scope.M09b = 'A zoológus teljes terjedelmében a kiképző- és kutatóállomáson van?';
    $scope.M09c = 'Hány trágya van teljes terjedelmében a kiképző- és kutatóállomáson??';
    $scope.M09d = 'Megjegyzés: Egy időben csak egy trágya szállítható.';
    $scope.M10 = 'Méhészet';
    $scope.M10a = 'A méh a kaptáron van és a kaptárban nincsen méz?';
    $scope.M10b = 'A méh a kaptáron van és a méz teljes terjedelmébe a bázison helyezkedik-e el?';
    $scope.M11 = 'Művégtag';
    $scope.M11a = 'A protézis a malacon van és nincsen a versenybírónál?';
    $scope.M11b = 'A protézis a malacon van és teljes terjedelmében a gazdaterületen van??';
    $scope.M12 = 'Fóka';
    $scope.M12a = 'A fóka teljesen a bázison van és nem törött?';
    $scope.M13 = 'Tej a bázison';
    $scope.M13a = 'A tej a bázison van?';
    $scope.M14 = 'Tej a rámpán';
    $scope.M14a = 'Mind a három tej a rámpán van?';
    $scope.M14b = 'Mind a három tej a rámpán van ÉS csak azok érintik a rámpát?';
    $scope.M14c = 'Mind a három tej a rámpán van ÉS csak azok érintik a rámpát ÉS mindegyik áll?';
    $scope.M15 = 'Trágyák';
    $scope.M15a = 'Mind a hét trágya teljes terjedelmében a kiképző- és kutatóállomáson van?';
    $scope.Penalty = 'Büntetőpontok';
    $scope.Penaltya = 'Hány darab trágya van a fehér háromszög alakú arénában??';

  });
} else if (language == "fr") {

  menuApp.controller("MenuCtrl", function($scope) {

    $scope.Yes = 'Oui';
    $scope.No = 'Non';
    $scope.Title = 'Calculateur de point “Animal Allies” (v2.0)';
    $scope.Scorer = 'Calculateur';
    $scope.Timers = 'Minuteurs';
    $scope.Saves = 'Sauvegardes';
    $scope.Points = 'Points';
      GraphTitle = 'Line Graph of Scores';
      GraphLegend = 'Scores';
    PointsLang = 'Points';
    $scope.Start = 'Démarrer';
    $scope.Reset = 'Redémarrer';
    $scope.Stop = 'Arrêter';
    $scope.SaveScore = 'Sauvegarder score';  
    $scope.LoadSave = 'Charger le score';  
    $scope.DeleteSave = 'Supprimer tous les scores';  
    DeletedSave = 'Vous avez supprimer tous les scores :-( !!!!';
    $scope.ImportSave = 'Importer les scores sauvegardés';
    $scope.ExportSave = 'Exporter les scores sauvegardés ';

    $scope.M01 = 'Transport de requin';
    $scope.M01a = 'L’aquarium et le requin sont-ils complètement dans la première zone ? (Rectangle gauche)';
    $scope.M01b = 'L’aquarium et le requin sont-ils complètement dans la seconde zone ? (Rectangle droit)';
    $scope.M01c = 'Le requin ne touche-t-il que le sol de l’aquarium ?';
    $scope.M01d = 'Note : Après le lancement, rien ne peut toucher le requin à l’exception de l’aquarium';
    $scope.M02 = 'Chien guide';
    $scope.M02a = 'La barrière d’avertissement est-elle vers le bas?';
    $scope.M02b = 'Note: La barrière doit être au sol puisque le robot l’a traversée depuis l’ouest, après être passé entre les barricades.';
    $scope.M03 = 'Preservation des animaux';
    $scope.M03a = 'Combien de paires d’animaux identiques comptez-vous sur chaque table?';
    $scope.M03b = 'Note: Chaque paire doit être créé avec une rotation sur base du modèle de préservation des animaux.';
      $scope.M04 = 'Alimentation';
    $scope.M04a = 'Combien d’éléments de nourriture sont complètement dans les zones cibles?';
    $scope.M04b = 'Note: S’il y a plusieurs éléments de nourriture dans une zone, ils doivent se correspondre.';
    $scope.M05 = 'Biomimétisme';
    $scope.M05a = 'Le mur de biomimétisme supporte-t-il tout le poids du gecko blanc?';
    $scope.M05b = 'Le mur de biomimétisme supporte-il tout le poids du robot?';
    $scope.M05c = 'Note: Pour qu’un objet rapporte des points, aucune de ses parties ne doit être en contact avec autre chose que le mur de biomimétisme et/ou le gecko vert, à l’exception de deux objets rapportant des points qui peuvent être en contact l’un avec l’autre.';
    $scope.M06 = 'Traite automatisée';
    $scope.M06a = 'Le lait et le fumier sont-ils tombés?';
    $scope.M06b = 'Tout le lait est-il tombé mais pas le fumier?';
    $scope.M06c = 'Note: L’unique action du robot pour déplacer le lait et/ou le fumier vient du mouvement du levier rouge';
    $scope.M07 = 'Libération des pandas';
    $scope.M07a = 'La plateforme est-elle complétetement ouverte dans le sens des aiguilles d’une montre?';
    $scope.M08 = 'Récupération de la camera';
    $scope.M08a = 'La camera est-elle complétement dans la base?';
    $scope.M09 = 'Entrainement et recherche';
    $scope.M09a = 'Le chien et le dresseur sont-ils complétement dans la zone d’entrainement et recherche?';
    $scope.M09b = 'Le zoologiste est-il complétement dans la zone d’entrainement et recherche?';
    $scope.M09c = 'Combien d’éléments de fumiers sont-ils dans la zone d’entrainement et recherche?';
    $scope.M09d = 'Note: Seul un élément de fumier peut être transporté à la fois';
    $scope.M10 = 'Apiculture';
    $scope.M10a = 'L’abeille est-elle sur la ruche sans qu’il n’y ait de miel dans la ruche?';
    $scope.M10b = 'L’abeille est-elle sur la ruche et le miel dans la base?';
    $scope.M11 = 'Prothèse';
    $scope.M11a = 'La prothèse est-elle sur l’animal et non tenue par l’arbitre?';
    $scope.M11b = 'La prothèse est-elle sur l’animal et l’animal dans sa zone (ferme)?';
    $scope.M12 = 'Phoque';
    $scope.M12a = 'Le phoque est-il complétement dans sa base, non abimé?';
    $scope.M13 = 'Lait dans la base';
    $scope.M13a = 'Les trois éléments de lait sont-ils complétement dans la base?';
    $scope.M14 = 'Lait sur la rampe';
    $scope.M14a = 'Les trois éléments de lait sont-ils complétement portés par la rampe?';
    $scope.M14b = 'Les trois éléments de lait sont-ils portés par la rampe ET sont les seules choses à toucher la rampe?';
    $scope.M14c = 'Les trois éléments sont-ils portés par la rampe ET sont les seules choses à toucher la rampe ET sont tous debout?';
    $scope.M15 = 'Les modèles';
    $scope.M15a = 'Les 7 modèles de fumier sont-ils complétement dans la zone d’entrainement et de recherche?';
    $scope.Penalty = 'Pénalités';
    $scope.Penaltya = 'Combien de pièces de fumier reste-t-il dans la zone triangulaire blanche?';

  });
} else {

  menuApp.controller("MenuCtrl", function($scope) {

    $scope.Yes = 'Yes';
    $scope.No = 'No';
    $scope.Title = 'Animal Allies Scorer (v2.0)';
    $scope.Scorer = 'Scorer';
    $scope.Timers = 'Timers';
    $scope.Saves = 'Saves';
    $scope.Points = 'Points';
      GraphTitle = 'Line Graph of Scores';
      GraphLegend = 'Scores';
    PointsLang = 'Points';
    $scope.Start = 'Start';
    $scope.Reset = 'Reset';
    $scope.Stop = 'Stop';
    $scope.SaveScore = 'Save Score';  
    $scope.LoadSave = 'Load Save';  
    $scope.DeleteSave = 'Delete All Saves!';  
    DeletedSave = 'Deleted all saves :-( !!!!';
    $scope.ImportSave = 'Import Saved Scores';
    $scope.ExportSave = 'Export Saved Scores';

    $scope.M01 = 'Shark Shipment';
    $scope.M01a = 'Is the Tank and the Shark completely in Target 1 (Left Box)?';
    $scope.M01b = 'Is the Tank and the Shark completely in Target 2 (Right Box)?';
    $scope.M01c = 'Is the Shark only touching the tank floor?';
    $scope.M01d = 'Note: After Launch, nothing is allowed to touch the Shark except the Tank.';
    $scope.M02 = 'Service Dog Action';
    $scope.M02a = 'Is the Warning Fence down?';
    $scope.M02b = 'Note: Fence must be down because the Robot completely crossed it from the west, after traveling between the Barriers.';
    $scope.M03 = 'Animal Conservation';
    $scope.M03a = 'How many identical pairs of Animals are on both tables?';
    $scope.M03b = 'Note: Each pair must be created through rotation of the Animal Conservation Mission Model.';
    $scope.M04 = 'Feeding';
    $scope.M04a = 'How many pieces of Food are completely in the target areas?';
    $scope.M04b = 'Note: If multiple pieces of Food are in one area, all must match each other.';
    $scope.M05 = 'Biomimicry';
    $scope.M05a = 'Does the Biomimicry Wall support all the weight of the White Gecko?';
    $scope.M05b = 'Does the Biomimicry Wall support all the weight of the robot?';
    $scope.M05c = 'Note: No part of a scoring object may be in contact with anything but the Biomimicry Wall and/or Green Gecko, except two scoring objects may be in contact with each other.';
    $scope.M06 = 'Milking Automation';
    $scope.M06a = 'Has Milk and Manure rolled out?';
    $scope.M06b = 'Has all the Milk rolled out but not the Manure?';
    $scope.M06c = 'Note: The Robot’s only movement of the Milk and/or Manure came by moving the red lever';
    $scope.M07 = 'Panda Release';
    $scope.M07a = 'Is the slider fully open clockwise?';
    $scope.M08 = 'Camera Recovery';
    $scope.M08a = 'Is the Camera completely in Base?';
    $scope.M09 = 'Training and Research';
    $scope.M09a = 'Are the Dog and Trainer completely in the Training and Research Area?';
    $scope.M09b = 'Is the Zoologist completely in the Training and Research Area?';
    $scope.M09c = 'How many Manure Samples are completely in the Training and Research Area?';
    $scope.M09d = 'Note: Only one Manure Sample may be Transported at a time';
    $scope.M10 = 'Beekeeping';
    $scope.M10a = 'Is the Bee on the Beehive and there is no Honey in the Beehive?';
    $scope.M10b = 'Is the Bee on the Beehive and Honey is in base?';
    $scope.M11 = 'Prosthesis';
    $scope.M11a = 'Is the Prosthesis fitted to the Pet AND not held by the Referee?';
    $scope.M11b = 'Is the Prosthesis fitted to the Pet AND the Pet is completely in its Farm Target?';
    $scope.M12 = 'Seal in Base';
    $scope.M12a = 'Is the Seal completely in Base and not broken?';
    $scope.M13 = 'Milk in Base';
    $scope.M13a = 'Are three Milk completely in Base?';
    $scope.M14 = 'Milk on Ramp';
    $scope.M14a = 'Are all three Milk completely supported by the Ramp?';
    $scope.M14b = 'Are all three Milk completely supported by the Ramp AND they are the only things touching the Ramp?';
    $scope.M14c = 'Are all three Milk completely supported by the Ramp AND they are the only things touching the Ramp AND they are all standing?';
    $scope.M15 = 'All Samples';
    $scope.M15a = 'Are all seven Manure Samples completely in the Training and Research Area?';
    $scope.Penalty = 'Penalty';
    $scope.Penaltya = 'How many Manure Samples are in the white triangle area?';

  });
}
